import { Inter, JetBrains_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import { GoogleOAuthProvider } from "@react-oauth/google";
import AuthProvider from "@/context/AuthProvider";
import { ToastContainer } from "react-toastify";

const inter = Inter({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-sans", // Use --font-sans for the main font
});

const jetbrains_mono = JetBrains_Mono({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-mono", // Use --font-mono for the monospace font
});

export const metadata: any = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const googleClientId = process.env.NEXT_PUBLIC_GOOGLE_CLIENT_ID || "";

  return (
    <html lang="en">
      <body className={`${inter.variable} ${jetbrains_mono.variable}`}>
        <AuthProvider>
          <GoogleOAuthProvider clientId={googleClientId}>
            <Navbar />
            {children}
            <ToastContainer autoClose={3000} />
            <Footer />
          </GoogleOAuthProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
